{ config, lib, pkgs, dotfilesPath, host, snappySwitcherPkg }:

let
  dotfilesSource = path: "${dotfilesPath}/${path}";
  staticConfigSources = lib.mapAttrs (_: source: { inherit source; }) {
    "hypr/hyprland.conf" = dotfilesSource "config/hypr/hyprland.conf";
    "hypr/appearance.conf" = dotfilesSource "config/hypr/appearance.conf";
    "hypr/autostart.conf" = dotfilesSource "config/hypr/autostart.conf";
    "hypr/input.conf" = dotfilesSource "config/hypr/input.conf";
    "hypr/keybinds.conf" = dotfilesSource "config/hypr/keybinds.conf";
    "hypr/rules.conf" = dotfilesSource "config/hypr/rules.conf";
    "hypr/hypridle.conf" = dotfilesSource "config/hypr/hypridle.conf";
    "hypr/hyprlock.conf" = dotfilesSource "config/hypr/hyprlock.conf";
    "hypr/plugins.conf" = dotfilesSource "config/hypr/plugins.conf";
    "alacritty/alacritty.toml" = dotfilesSource "config/alacritty/alacritty.toml";
    "ghostty/config" = dotfilesSource "config/ghostty/config";
    "tmux/tmux.conf" = dotfilesSource "config/tmux/tmux.conf";
    "git/ignore" = dotfilesSource "config/git/ignore";
    "vicinae/settings.json" = dotfilesSource "config/vicinae/settings.json";
    "zathura/zathurarc" = dotfilesSource "config/zathura/zathurarc";
  };
  recursiveConfigSources = lib.mapAttrs (_: source: {
    inherit source;
    recursive = true;
  }) {
    quickshell = dotfilesSource "config/quickshell";
    nvim = dotfilesSource "config/nvim";
  };
  mkHostConfigFile = key: fallback:
    let
      relativePath = host.hyprland.${key};
    in
    if relativePath == null then
      { text = fallback; }
    else
      { source = dotfilesSource relativePath; };
in
{
  xdg.configFile = staticConfigSources // recursiveConfigSources // {
    "hypr/autostart-host.conf" = mkHostConfigFile "autostartHost" "";
    "hypr/input-devices.conf" = mkHostConfigFile "inputDevices" "";
    "hypr/monitors.conf" = mkHostConfigFile "monitors" "monitor = ,preferred,auto,1\n";
    "hypr/env.conf" = mkHostConfigFile "env" "";

    # Route file picker to KDE, everything else through Hyprland -> GTK fallback.
    "xdg-desktop-portal/portals.conf".text = ''
      [preferred]
      default = hyprland;gtk
      org.freedesktop.impl.portal.FileChooser = kde
    '';

    # Snappy Switcher config.ini is generated by desktopctl; only the packaged
    # themes stay symlinked.
    "snappy-switcher/themes".source = "${snappySwitcherPkg}/share/snappy-switcher/themes";

    "wireplumber/wireplumber.conf.d/50-bluetooth.conf".text = ''
      monitor.bluez.properties = {
        bluez5.enable-sbc-xq = true
        bluez5.enable-msbc = true
        bluez5.enable-hw-volume = true
      }
    '';
  };

  xdg.desktopEntries.code = {
    name = "Visual Studio Code";
    comment = "Code Editing. Redefined.";
    genericName = "Text Editor";
    icon = "vscode";
    exec = "hyprctl dispatch exec code %F";
    categories = [ "Utility" "TextEditor" "Development" "IDE" ];
    startupNotify = true;
    settings = {
      Keywords = "vscode";
      StartupWMClass = "Code";
      Version = "1.5";
    };
    actions = {
      new-empty-window = {
        name = "New Empty Window";
        icon = "vscode";
        exec = "hyprctl dispatch exec -- code --new-window %F";
      };
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = "chromium-browser.desktop";
      "x-scheme-handler/http" = "chromium-browser.desktop";
      "x-scheme-handler/https" = "chromium-browser.desktop";
      "application/pdf" = "chromium-browser.desktop";
      "inode/directory" = "org.gnome.Nautilus.desktop";
      "image/png" = "imv.desktop";
      "image/jpeg" = "imv.desktop";
      "image/jpg" = "imv.desktop";
      "image/gif" = "imv.desktop";
      "image/webp" = "imv.desktop";
      "image/svg+xml" = "imv.desktop";
      "image/heic" = "org.kde.gwenview.desktop";
      "image/heif" = "org.kde.gwenview.desktop";
      "image/heic-sequence" = "org.kde.gwenview.desktop";
      "image/heif-sequence" = "org.kde.gwenview.desktop";
      "video/mp4" = "org.kde.haruna.desktop";
      "video/x-matroska" = "org.kde.haruna.desktop";
      "video/x-msvideo" = "org.kde.haruna.desktop";
      "video/webm" = "org.kde.haruna.desktop";
      "text/plain" = "org.gnome.gedit.desktop";
      "x-scheme-handler/mailto" = "thunderbird.desktop";
      "x-scheme-handler/terminal" = "Alacritty.desktop";
    };
  };
}
