use super::{Assembly, GeneratedContent, TargetMetadata};
use crate::theme::schema::{ColorScheme, ThemeState};

pub const METADATA: TargetMetadata = TargetMetadata {
    name: "alacritty",
    assembly: Assembly::Import,
    output_path: Some("~/.config/alacritty/theme.toml"),
    base_path: None,
    extra_outputs: &[],
    reload_cmd: None,
    comment: Some("#"),
    sync_safe: true,
};

pub fn generate(colors: &ColorScheme, state: &ThemeState) -> crate::Result<GeneratedContent> {
    Ok(GeneratedContent::text(format!(
        concat!(
            "[font]\n",
            "normal = {{ family = \"{}\" }}\n",
            "size = {}\n",
            "\n",
            "[colors.primary]\n",
            "background = \"{}\"\n",
            "foreground = \"{}\"\n",
            "\n",
            "[colors.normal]\n",
            "black   = \"{}\"\n",
            "red     = \"{}\"\n",
            "green   = \"{}\"\n",
            "yellow  = \"{}\"\n",
            "blue    = \"{}\"\n",
            "magenta = \"{}\"\n",
            "cyan    = \"{}\"\n",
            "white   = \"{}\"\n",
            "\n",
            "[colors.bright]\n",
            "black   = \"{}\"\n",
            "red     = \"{}\"\n",
            "green   = \"{}\"\n",
            "yellow  = \"{}\"\n",
            "blue    = \"{}\"\n",
            "magenta = \"{}\"\n",
            "cyan    = \"{}\"\n",
            "white   = \"{}\"\n",
        ),
        state.mono_font,
        state.mono_font_size_for(METADATA.name)?,
        colors.bg,
        colors.fg,
        colors.palette[0],
        colors.palette[1],
        colors.palette[2],
        colors.palette[3],
        colors.palette[4],
        colors.palette[5],
        colors.palette[6],
        colors.palette[7],
        colors.palette[8],
        colors.palette[9],
        colors.palette[10],
        colors.palette[11],
        colors.palette[12],
        colors.palette[13],
        colors.palette[14],
        colors.palette[15],
    )))
}
