use super::{Assembly, GeneratedContent, TargetMetadata};
use crate::theme::{
    atomic_write, expand_user_path, json,
    schema::{ColorScheme, ThemeState},
};
use serde_json::{Map, Value};
use std::{fs, io, path::Path};

pub const METADATA: TargetMetadata = TargetMetadata::new(
    "openchamber",
    Assembly::Command,
    &["color_scheme", "system_font", "mono_font"],
)
.managed_paths(&[
    "~/.config/openchamber/settings.json",
    "~/.config/openchamber/themes/desktopctl.json",
]);

const SETTINGS_PATH: &str = "~/.config/openchamber/settings.json";
const THEME_OUTPUT_PATH: &str = "~/.config/openchamber/themes/desktopctl.json";
const THEME_ID: &str = "desktopctl";

pub fn generate(_colors: &ColorScheme, _state: &ThemeState) -> crate::Result<GeneratedContent> {
    Ok(GeneratedContent::commands(Vec::new()))
}

pub fn persist(colors: &ColorScheme, state: &ThemeState) -> crate::Result<()> {
    write_theme(&expand_user_path(THEME_OUTPUT_PATH)?, colors, state)?;
    write_settings(&expand_user_path(SETTINGS_PATH)?, colors)
}

fn write_theme(path: &Path, colors: &ColorScheme, state: &ThemeState) -> crate::Result<()> {
    atomic_write(path, render_theme(colors, state).as_bytes())
}

fn write_settings(path: &Path, colors: &ColorScheme) -> crate::Result<()> {
    let mut root = load_json_object(path)?;
    let variant = theme_variant(colors);

    root["themeId"] = Value::String(THEME_ID.to_owned());
    root["themeVariant"] = Value::String(variant.to_owned());
    root["useSystemTheme"] = Value::Bool(false);
    root[if colors.is_dark() {
        "darkThemeId"
    } else {
        "lightThemeId"
    }] = Value::String(THEME_ID.to_owned());

    atomic_write(path, json::format_pretty_value(&root).as_bytes())
}

// OpenChamber owns the rest of settings.json, so any failure to read it back
// must abort the patch instead of replacing the file with only theme keys.
fn load_json_object(path: &Path) -> crate::Result<Value> {
    if !path.exists() {
        return Ok(Value::Object(Map::new()));
    }

    let text = fs::read_to_string(path)?;
    if text.trim().is_empty() {
        return Ok(Value::Object(Map::new()));
    }

    let value: Value = serde_json::from_str(&text).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("Invalid JSON in {}: {error}", path.display()),
        )
    })?;

    if !value.is_object() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{}: expected top-level JSON object", path.display()),
        )
        .into());
    }

    Ok(value)
}

fn render_theme(colors: &ColorScheme, state: &ThemeState) -> String {
    let emphasis_foreground = emphasis_foreground(colors);

    let mut metadata = Map::new();
    metadata.insert("id".to_owned(), Value::String(THEME_ID.to_owned()));
    metadata.insert(
        "name".to_owned(),
        Value::String(format!("Desktopctl {}", title_variant(colors))),
    );
    metadata.insert(
        "description".to_owned(),
        Value::String("Theme generated by desktopctl".to_owned()),
    );
    metadata.insert("version".to_owned(), Value::String("1.0.0".to_owned()));
    metadata.insert(
        "variant".to_owned(),
        Value::String(theme_variant(colors).to_owned()),
    );
    metadata.insert(
        "tags".to_owned(),
        Value::Array(vec![
            Value::String(theme_variant(colors).to_owned()),
            Value::String("desktopctl".to_owned()),
            Value::String(colors.family.clone()),
        ]),
    );

    let mut primary = Map::new();
    primary.insert("base".to_owned(), Value::String(colors.accent.clone()));
    primary.insert(
        "hover".to_owned(),
        Value::String(colors.blue_bright.clone()),
    );
    primary.insert("active".to_owned(), Value::String(colors.blue.clone()));
    primary.insert(
        "foreground".to_owned(),
        Value::String(emphasis_foreground.clone()),
    );
    primary.insert(
        "muted".to_owned(),
        Value::String(with_alpha(&colors.accent, "80")),
    );
    primary.insert(
        "emphasis".to_owned(),
        Value::String(colors.blue_bright.clone()),
    );

    let mut surface = Map::new();
    surface.insert("background".to_owned(), Value::String(colors.bg.clone()));
    surface.insert("foreground".to_owned(), Value::String(colors.fg.clone()));
    surface.insert(
        "muted".to_owned(),
        Value::String(with_alpha(&colors.bg_dim, "90")),
    );
    surface.insert(
        "mutedForeground".to_owned(),
        Value::String(colors.fg3.clone()),
    );
    surface.insert(
        "elevated".to_owned(),
        Value::String(with_alpha(&colors.bg1, "90")),
    );
    surface.insert(
        "elevatedForeground".to_owned(),
        Value::String(colors.fg.clone()),
    );
    surface.insert(
        "overlay".to_owned(),
        Value::String(with_alpha(&colors.bg, "80")),
    );
    surface.insert("subtle".to_owned(), Value::String(colors.bg2.clone()));

    let mut interactive = Map::new();
    interactive.insert("border".to_owned(), Value::String(colors.bg3.clone()));
    interactive.insert("borderHover".to_owned(), Value::String(colors.fg4.clone()));
    interactive.insert(
        "borderFocus".to_owned(),
        Value::String(colors.accent.clone()),
    );
    interactive.insert(
        "selection".to_owned(),
        Value::String(with_alpha(&colors.accent, "26")),
    );
    interactive.insert(
        "selectionForeground".to_owned(),
        Value::String(colors.fg.clone()),
    );
    interactive.insert("focus".to_owned(), Value::String(colors.accent.clone()));
    interactive.insert(
        "focusRing".to_owned(),
        Value::String(with_alpha(&colors.accent, "50")),
    );
    interactive.insert("cursor".to_owned(), Value::String(colors.fg.clone()));
    interactive.insert(
        "hover".to_owned(),
        Value::String(with_alpha(&colors.fg, "12")),
    );
    interactive.insert(
        "active".to_owned(),
        Value::String(with_alpha(&colors.fg, "18")),
    );

    let mut status = Map::new();
    insert_status_group(
        &mut status,
        "error",
        &colors.red,
        &emphasis_foreground,
        "20",
        "50",
    );
    insert_status_group(
        &mut status,
        "warning",
        &colors.yellow,
        &emphasis_foreground,
        "20",
        "50",
    );
    insert_status_group(
        &mut status,
        "success",
        &colors.green,
        &emphasis_foreground,
        "20",
        "50",
    );
    insert_status_group(
        &mut status,
        "info",
        &colors.blue,
        &emphasis_foreground,
        "20",
        "50",
    );

    let mut pr = Map::new();
    pr.insert("open".to_owned(), Value::String(colors.green.clone()));
    pr.insert("draft".to_owned(), Value::String(colors.fg3.clone()));
    pr.insert("blocked".to_owned(), Value::String(colors.yellow.clone()));
    pr.insert("merged".to_owned(), Value::String(colors.purple.clone()));
    pr.insert("closed".to_owned(), Value::String(colors.red.clone()));

    let mut syntax_base = Map::new();
    syntax_base.insert("background".to_owned(), Value::String(colors.bg1.clone()));
    syntax_base.insert("foreground".to_owned(), Value::String(colors.fg.clone()));
    syntax_base.insert("comment".to_owned(), Value::String(colors.fg4.clone()));
    syntax_base.insert("keyword".to_owned(), Value::String(colors.purple.clone()));
    syntax_base.insert("string".to_owned(), Value::String(colors.green.clone()));
    syntax_base.insert("number".to_owned(), Value::String(colors.orange.clone()));
    syntax_base.insert("function".to_owned(), Value::String(colors.blue.clone()));
    syntax_base.insert("variable".to_owned(), Value::String(colors.fg.clone()));
    syntax_base.insert("type".to_owned(), Value::String(colors.cyan.clone()));
    syntax_base.insert("operator".to_owned(), Value::String(colors.accent.clone()));

    let mut syntax_highlights = Map::new();
    syntax_highlights.insert("diffAdded".to_owned(), Value::String(colors.green.clone()));
    syntax_highlights.insert(
        "diffAddedBackground".to_owned(),
        Value::String(with_alpha(&colors.green, "20")),
    );
    syntax_highlights.insert("diffRemoved".to_owned(), Value::String(colors.red.clone()));
    syntax_highlights.insert(
        "diffRemovedBackground".to_owned(),
        Value::String(with_alpha(&colors.red, "20")),
    );
    syntax_highlights.insert(
        "diffModified".to_owned(),
        Value::String(colors.blue.clone()),
    );
    syntax_highlights.insert(
        "diffModifiedBackground".to_owned(),
        Value::String(with_alpha(&colors.blue, "20")),
    );
    syntax_highlights.insert("lineNumber".to_owned(), Value::String(colors.fg4.clone()));
    syntax_highlights.insert(
        "lineNumberActive".to_owned(),
        Value::String(colors.fg.clone()),
    );

    let mut syntax = Map::new();
    syntax.insert("base".to_owned(), Value::Object(syntax_base));
    syntax.insert("highlights".to_owned(), Value::Object(syntax_highlights));

    let mut markdown = Map::new();
    markdown.insert("heading1".to_owned(), Value::String(colors.accent.clone()));
    markdown.insert("heading2".to_owned(), Value::String(colors.blue.clone()));
    markdown.insert("heading3".to_owned(), Value::String(colors.fg.clone()));
    markdown.insert("heading4".to_owned(), Value::String(colors.fg.clone()));
    markdown.insert("link".to_owned(), Value::String(colors.blue.clone()));
    markdown.insert(
        "linkHover".to_owned(),
        Value::String(colors.blue_bright.clone()),
    );
    markdown.insert("inlineCode".to_owned(), Value::String(colors.green.clone()));
    markdown.insert(
        "inlineCodeBackground".to_owned(),
        Value::String(colors.bg1.clone()),
    );
    markdown.insert("blockquote".to_owned(), Value::String(colors.fg3.clone()));
    markdown.insert(
        "blockquoteBorder".to_owned(),
        Value::String(colors.bg3.clone()),
    );
    markdown.insert(
        "listMarker".to_owned(),
        Value::String(colors.yellow.clone()),
    );

    let mut chat = Map::new();
    chat.insert("userMessage".to_owned(), Value::String(colors.fg.clone()));
    chat.insert(
        "userMessageBackground".to_owned(),
        Value::String(colors.bg1.clone()),
    );
    chat.insert(
        "assistantMessage".to_owned(),
        Value::String(colors.fg.clone()),
    );
    chat.insert(
        "assistantMessageBackground".to_owned(),
        Value::String(colors.bg.clone()),
    );
    chat.insert("timestamp".to_owned(), Value::String(colors.fg4.clone()));
    chat.insert("divider".to_owned(), Value::String(colors.bg3.clone()));

    let mut tool_edit = Map::new();
    tool_edit.insert("added".to_owned(), Value::String(colors.green.clone()));
    tool_edit.insert(
        "addedBackground".to_owned(),
        Value::String(with_alpha(&colors.green, "25")),
    );
    tool_edit.insert("removed".to_owned(), Value::String(colors.red.clone()));
    tool_edit.insert(
        "removedBackground".to_owned(),
        Value::String(with_alpha(&colors.red, "25")),
    );
    tool_edit.insert("lineNumber".to_owned(), Value::String(colors.fg4.clone()));

    let mut tools = Map::new();
    tools.insert(
        "background".to_owned(),
        Value::String(with_alpha(&colors.bg1, "50")),
    );
    tools.insert("border".to_owned(), Value::String(colors.bg3.clone()));
    tools.insert(
        "headerHover".to_owned(),
        Value::String(with_alpha(&colors.fg, "08")),
    );
    tools.insert("icon".to_owned(), Value::String(colors.fg3.clone()));
    tools.insert("title".to_owned(), Value::String(colors.fg.clone()));
    tools.insert("description".to_owned(), Value::String(colors.fg3.clone()));
    tools.insert("edit".to_owned(), Value::Object(tool_edit));

    let mut colors_root = Map::new();
    colors_root.insert("primary".to_owned(), Value::Object(primary));
    colors_root.insert("surface".to_owned(), Value::Object(surface));
    colors_root.insert("interactive".to_owned(), Value::Object(interactive));
    colors_root.insert("status".to_owned(), Value::Object(status));
    colors_root.insert("pr".to_owned(), Value::Object(pr));
    colors_root.insert("syntax".to_owned(), Value::Object(syntax));
    colors_root.insert("markdown".to_owned(), Value::Object(markdown));
    colors_root.insert("chat".to_owned(), Value::Object(chat));
    colors_root.insert("tools".to_owned(), Value::Object(tools));

    let mut fonts = Map::new();
    fonts.insert(
        "sans".to_owned(),
        Value::String(format!(
            "{}, sans-serif",
            css_font_family(&state.system_font)
        )),
    );
    fonts.insert(
        "mono".to_owned(),
        Value::String(format!("{}, monospace", css_font_family(&state.mono_font))),
    );
    fonts.insert(
        "heading".to_owned(),
        Value::String(format!(
            "{}, sans-serif",
            css_font_family(&state.system_font)
        )),
    );

    let mut config = Map::new();
    config.insert("fonts".to_owned(), Value::Object(fonts));

    let mut root = Map::new();
    root.insert("metadata".to_owned(), Value::Object(metadata));
    root.insert("colors".to_owned(), Value::Object(colors_root));
    root.insert("config".to_owned(), Value::Object(config));

    format!("{}\n", json::format_pretty_value(&Value::Object(root)))
}

fn theme_variant(colors: &ColorScheme) -> &'static str {
    if colors.is_dark() { "dark" } else { "light" }
}

fn title_variant(colors: &ColorScheme) -> &'static str {
    if colors.is_dark() { "Dark" } else { "Light" }
}

fn emphasis_foreground(colors: &ColorScheme) -> String {
    if colors.is_dark() {
        colors.bg.clone()
    } else {
        colors.fg.clone()
    }
}

fn css_font_family(name: &str) -> String {
    format!("'{}'", name.replace('\\', "\\\\").replace('\'', "\\'"))
}

fn with_alpha(color: &str, alpha: &str) -> String {
    match color.len() {
        7 => format!("{color}{alpha}"),
        9 => format!("{}{alpha}", &color[..7]),
        _ => color.to_owned(),
    }
}

fn insert_status_group(
    status: &mut Map<String, Value>,
    prefix: &str,
    color: &str,
    foreground: &str,
    background_alpha: &str,
    border_alpha: &str,
) {
    status.insert(prefix.to_owned(), Value::String(color.to_owned()));
    status.insert(
        format!("{prefix}Foreground"),
        Value::String(foreground.to_owned()),
    );
    status.insert(
        format!("{prefix}Background"),
        Value::String(with_alpha(color, background_alpha)),
    );
    status.insert(
        format!("{prefix}Border"),
        Value::String(with_alpha(color, border_alpha)),
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::targets::testsupport::{dummy_colors, dummy_state, rose_pine_dawn_colors};
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn temp_path(name: &str) -> std::path::PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time works")
            .as_nanos();
        std::env::temp_dir().join(format!("desktopctl-{name}-{nanos}.json"))
    }

    #[test]
    fn theme_file_matches_expected_shape() {
        let rendered = render_theme(&dummy_colors(), &dummy_state());
        let value: Value = serde_json::from_str(&rendered).expect("valid json");

        assert_eq!(value["metadata"]["id"], Value::String(THEME_ID.to_owned()));
        assert_eq!(
            value["metadata"]["variant"],
            Value::String("dark".to_owned())
        );
        assert_eq!(
            value["colors"]["surface"]["elevated"],
            Value::String("#02020290".to_owned())
        );
        assert_eq!(
            value["colors"]["primary"]["foreground"],
            Value::String("#000000".to_owned())
        );
        assert_eq!(
            value["config"]["fonts"]["sans"],
            Value::String("'Overpass', sans-serif".to_owned())
        );
    }

    #[test]
    fn theme_file_uses_ascii_json_escaping() {
        let rendered = render_theme(&rose_pine_dawn_colors(), &dummy_state());
        assert!(rendered.is_ascii(), "{rendered}");
    }

    #[test]
    fn write_settings_preserves_unmanaged_keys() {
        let path = temp_path("openchamber-settings-write");
        fs::write(&path, r#"{"desktopLocalPort":57123,"themeId":"old"}"#).expect("fixture written");

        write_settings(&path, &dummy_colors()).expect("write succeeds");
        let value: Value =
            serde_json::from_str(&fs::read_to_string(&path).expect("settings exist"))
                .expect("valid settings json");

        assert_eq!(value["desktopLocalPort"], Value::from(57_123));
        assert_eq!(value["themeId"], Value::String(THEME_ID.to_owned()));
        assert_eq!(value["themeVariant"], Value::String("dark".to_owned()));
        assert_eq!(value["useSystemTheme"], Value::Bool(false));
        assert_eq!(value["darkThemeId"], Value::String(THEME_ID.to_owned()));

        let _ = fs::remove_file(path);
    }

    #[test]
    fn write_settings_leaves_invalid_settings_file_untouched() {
        let path = temp_path("openchamber-settings-invalid");
        fs::write(&path, "not json").expect("fixture written");

        let result = write_settings(&path, &dummy_colors());

        assert!(result.is_err(), "invalid settings.json must fail loudly");
        assert_eq!(
            fs::read_to_string(&path).expect("settings still exist"),
            "not json"
        );

        let _ = fs::remove_file(path);
    }
}
