-- Appearance

-- Theme-driven appearance values, generated by `desktopctl theme`.
local theme = require("./appearance-theme")

hl.config({
    general = {
        layout = "dwindle",
        allow_tearing = false,

        gaps_in = theme.gaps_in,
        gaps_out = theme.gaps_out,
        border_size = theme.border_size,
    },

    decoration = {
        rounding = theme.rounding,

        blur = {
            enabled = theme.blur_enabled,
            size = theme.blur_size,
            passes = theme.blur_passes,
        },
    },

    animations = {
        enabled = theme.animations_enabled,
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",    enabled = true, speed = 4,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4,  bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "myBezier" })
hl.animation({ leaf = "fade",       enabled = true, speed = 4,  bezier = "myBezier" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4,  bezier = "myBezier" })
