# Session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprpolkitagent
exec-once = brightnessctl -d intel_backlight -m > /tmp/quickshell-brightness

exec-once = qs

# Wallpaper
exec-once = swww-daemon && sleep 0.5 && swww img ~/repos/dotfiles/wallpapers/lmao.png

# Idle & lock
exec-once = hypridle

# App launcher — vicinae not yet packaged for NixOS
# exec = pkill vicinae; vicinae server

# Audio
exec-once = easyeffects --gapplication-service