plugin {
    hyprbars {
        bar_height = 24
        bar_color = $theme_bg1
        bar_text_color = $theme_fg
        bar_font_family = $theme_sys_font
        bar_font_size = 10
        bar_buttons_alignment = left
        bar_button_padding = 8

        hyprbars-button = $theme_red, 14, , hyprctl dispatch killactive
        hyprbars-button = $theme_yellow, 14, , hyprctl dispatch fullscreen 1
        hyprbars-button = $theme_green, 14, , hyprctl dispatch movetoworkspacesilent special
    }

    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = $theme_bg
        workspace_method = first 1
    }
}