# Hyprland plugins
# HYPR_PLUGIN_DIR is provided by the NixOS system configuration.

plugin = $HYPR_PLUGIN_DIR/lib/libhyprbars.so
plugin = $HYPR_PLUGIN_DIR/lib/libhyprexpo.so

plugin {
    hyprbars {
        bar_height = 24
        bar_color = $theme_bg1_rgba
        col.text = $theme_fg_rgba
        bar_text_font = $theme_sys_font
        bar_text_size = 10
        bar_buttons_alignment = left
        bar_button_padding = 8
        on_double_click = hyprctl dispatch fullscreen 1

        hyprbars-button = $theme_red_rgba, 14, , hyprctl dispatch killactive
        hyprbars-button = $theme_yellow_rgba, 14, , hyprctl dispatch fullscreen 1
        hyprbars-button = $theme_green_rgba, 14, , hyprctl dispatch movetoworkspacesilent special
    }

    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = $theme_bg_rgba
        workspace_method = first 1
    }
}
