# Window Rules

# Float utility windows
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class xdg-desktop-portal-gtk, match:title (Open Files), float on, size 800 600, center on

# Layer Rules
# Quickshell blur (uncomment when Quickshell is running)
# layerrule = match:namespace quickshell:.*, blur on
# layerrule = match:namespace quickshell:.*, ignorealpha 0.79

# Disable hyprbars on tiled windows (bars only on floating)
# windowrule {
#     name = no-hyprbars-on-tiled
#     hyprbars:no_bar = true
#     match:float = 0
# }

layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}