-- Palette comes from `desktopctl theme` (see docs/theming.md); this file owns
-- only the role -> colour mapping, kept in step with the gtksourceview target
-- so both editors render the same scheme the same way.
local theme = require("theme-colors")
local c = theme.colors

vim.o.background = theme.background
vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd.syntax("reset")
end
vim.g.colors_name = "desktopctl"

for index, color in ipairs(theme.terminal) do
  vim.g["terminal_color_" .. (index - 1)] = color
end

local groups = {
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = c.fg, bg = c.bg_dim },
  FloatBorder = { fg = c.bg3, bg = c.bg_dim },
  FloatTitle = { fg = c.accent, bg = c.bg_dim, bold = true },
  Cursor = { fg = c.bg, bg = c.fg },
  lCursor = { link = "Cursor" },
  TermCursor = { link = "Cursor" },
  CursorLine = { bg = c.bg_dim },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = c.bg1 },
  CursorLineNr = { fg = c.accent, bold = true },
  LineNr = { fg = c.fg4 },
  SignColumn = { fg = c.fg4, bg = c.bg },
  FoldColumn = { fg = c.fg4, bg = c.bg },
  Folded = { fg = c.fg3, bg = c.bg1 },
  WinSeparator = { fg = c.bg2 },
  Visual = { bg = c.bg2 },
  VisualNOS = { link = "Visual" },
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.orange },
  CurSearch = { link = "IncSearch" },
  Substitute = { fg = c.bg, bg = c.red },
  MatchParen = { fg = c.bg, bg = c.fg4, bold = true },
  Pmenu = { fg = c.fg, bg = c.bg_dim },
  PmenuSel = { fg = c.bg, bg = c.accent, bold = true },
  PmenuSbar = { bg = c.bg1 },
  PmenuThumb = { bg = c.bg3 },
  PmenuKind = { fg = c.purple, bg = c.bg_dim },
  PmenuKindSel = { link = "PmenuSel" },
  PmenuExtra = { fg = c.fg3, bg = c.bg_dim },
  PmenuExtraSel = { link = "PmenuSel" },
  WildMenu = { link = "PmenuSel" },
  StatusLine = { fg = c.fg, bg = c.bg1 },
  StatusLineNC = { fg = c.fg4, bg = c.bg_dim },
  TabLine = { fg = c.fg3, bg = c.bg_dim },
  TabLineFill = { bg = c.bg_dim },
  TabLineSel = { fg = c.fg, bg = c.bg },
  WinBar = { fg = c.fg2, bg = c.bg },
  WinBarNC = { fg = c.fg4, bg = c.bg },
  Title = { fg = c.accent, bold = true },
  Directory = { fg = c.blue },
  Question = { fg = c.green },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = c.fg, bold = true },
  ErrorMsg = { fg = c.red, bold = true },
  WarningMsg = { fg = c.orange, bold = true },
  NonText = { fg = c.fg_faint },
  Whitespace = { fg = c.fg_faint },
  SpecialKey = { fg = c.fg4 },
  EndOfBuffer = { fg = c.bg },
  Conceal = { fg = c.fg4 },
  QuickFixLine = { bg = c.bg1, bold = true },
  SpellBad = { sp = c.red, undercurl = true },
  SpellCap = { sp = c.blue, undercurl = true },
  SpellLocal = { sp = c.cyan, undercurl = true },
  SpellRare = { sp = c.purple, undercurl = true },
  DiffAdd = { fg = c.green, bg = c.bg1 },
  DiffChange = { fg = c.yellow, bg = c.bg1 },
  DiffDelete = { fg = c.red, bg = c.bg1 },
  DiffText = { fg = c.bg, bg = c.yellow },
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red },

  Comment = { fg = c.fg3, italic = true },
  SpecialComment = { fg = c.fg2, italic = true },
  Constant = { fg = c.cyan },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.purple },
  Boolean = { fg = c.purple },
  Float = { fg = c.purple },
  Identifier = { fg = c.blue },
  Function = { fg = c.blue_bright },
  Statement = { fg = c.red },
  Operator = { fg = c.orange },
  PreProc = { fg = c.purple },
  Type = { fg = c.yellow },
  Special = { fg = c.orange },
  Delimiter = { fg = c.fg2 },
  Debug = { fg = c.red },
  Underlined = { fg = c.blue, underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Ignore = { fg = c.fg_faint },
  Error = { fg = c.red, bold = true, underline = true },
  Todo = { fg = c.bg, bg = c.yellow, bold = true },

  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.red },
  ["@variable.parameter"] = { fg = c.fg2 },
  ["@variable.member"] = { fg = c.blue },
  ["@constant.builtin"] = { fg = c.purple },
  ["@module"] = { fg = c.yellow },
  ["@constructor"] = { fg = c.yellow },
  ["@function.builtin"] = { fg = c.blue_bright },
  ["@keyword.operator"] = { fg = c.orange },
  ["@punctuation.delimiter"] = { fg = c.fg2 },
  ["@punctuation.bracket"] = { fg = c.fg2 },
  ["@punctuation.special"] = { fg = c.orange },
  ["@string.escape"] = { fg = c.orange },
  ["@string.special"] = { fg = c.orange },
  ["@comment.error"] = { fg = c.red, bold = true },
  ["@comment.warning"] = { fg = c.orange, bold = true },
  ["@comment.note"] = { fg = c.blue_bright, bold = true },
  ["@comment.todo"] = { link = "Todo" },
  ["@tag"] = { fg = c.red },
  ["@tag.attribute"] = { fg = c.yellow },
  ["@tag.delimiter"] = { fg = c.fg2 },
  ["@markup.heading"] = { fg = c.accent, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.link"] = { fg = c.blue, underline = true },
  ["@markup.raw"] = { fg = c.green },
  ["@markup.list"] = { fg = c.orange },
  ["@markup.quote"] = { fg = c.fg3, italic = true },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.minus"] = { fg = c.red },
  ["@diff.delta"] = { fg = c.yellow },

  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.orange },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
  DiagnosticUnnecessary = { fg = c.fg4, undercurl = true, sp = c.fg4 },
  LspReferenceText = { bg = c.bg1 },
  LspReferenceRead = { bg = c.bg1 },
  LspReferenceWrite = { bg = c.bg1, bold = true },
  LspInlayHint = { fg = c.fg4, italic = true },
  LspCodeLens = { fg = c.fg4 },
  LspSignatureActiveParameter = { fg = c.accent, bold = true },

  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.yellow },
  GitSignsDelete = { fg = c.red },
  GitSignsCurrentLineBlame = { fg = c.fg_faint, italic = true },

  TelescopeNormal = { fg = c.fg, bg = c.bg_dim },
  TelescopeBorder = { fg = c.bg3, bg = c.bg_dim },
  TelescopeTitle = { fg = c.bg, bg = c.accent, bold = true },
  TelescopePromptNormal = { fg = c.fg, bg = c.bg1 },
  TelescopePromptBorder = { fg = c.bg1, bg = c.bg1 },
  TelescopePromptPrefix = { fg = c.accent, bg = c.bg1 },
  TelescopeSelection = { fg = c.fg, bg = c.bg2, bold = true },
  TelescopeMatching = { fg = c.orange, bold = true },

  NvimTreeNormal = { fg = c.fg, bg = c.bg_dim },
  NvimTreeWinSeparator = { fg = c.bg2, bg = c.bg_dim },
  NvimTreeCursorLine = { bg = c.bg1 },
  NvimTreeRootFolder = { fg = c.accent, bold = true },
  NvimTreeFolderIcon = { fg = c.blue },
  NvimTreeFolderName = { fg = c.blue },
  NvimTreeOpenedFolderName = { fg = c.blue, bold = true },
  NvimTreeSpecialFile = { fg = c.purple },
  NvimTreeIndentMarker = { fg = c.bg3 },
  NvimTreeGitNewIcon = { fg = c.green },
  NvimTreeGitDirtyIcon = { fg = c.yellow },
  NvimTreeGitDeletedIcon = { fg = c.red },

  CmpItemAbbr = { fg = c.fg2 },
  CmpItemAbbrMatch = { fg = c.accent, bold = true },
  CmpItemAbbrDeprecated = { fg = c.fg4, strikethrough = true },
  CmpItemKind = { fg = c.purple },
  CmpItemMenu = { fg = c.fg3 },

  IblIndent = { fg = c.bg1 },
  IblScope = { fg = c.bg3 },

  NavicText = { fg = c.fg2 },
  NavicSeparator = { fg = c.fg4 },

  DashboardHeader = { fg = c.accent },
  DashboardIcon = { fg = c.purple },
  DashboardDesc = { fg = c.fg },
  DashboardKey = { fg = c.orange },
  DashboardShortCut = { fg = c.cyan },
  DashboardFooter = { fg = c.fg3 },

  CopilotSuggestion = { fg = c.fg_faint, italic = true },
  CopilotAnnotation = { fg = c.fg4 },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end
