"""Orchestrator — runs targets using the correct assembly strategy."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType

from .schema import ColorScheme, ThemeState
from .targets import REGISTRY

# ── Dependency map: state key -> set of target names ─────────────────────
DEPENDS: dict[str, set[str]] = {
    "color_scheme": {
        "alacritty", "ghostty", "hyprland", "zathura", "quickshell",
        "neovim", "starship", "tmux", "gtk", "qt", "vicinae", "bat",
        "wallpaper",
        "snappy_switcher",
    },
    "wallpaper":      {"wallpaper"},
    "filter_wallpaper": {"wallpaper"},
    "system_font":    {"quickshell", "gtk", "qt", "vicinae", "snappy_switcher"},
    "mono_font":      {"alacritty", "ghostty", "quickshell", "qt", "tmux"},
    "icon_theme":     {"gtk", "qt", "snappy_switcher"},
    "cursor_theme":   {"cursor"},
    "cursor_size":    {"cursor"},
    "font_size":      {"gtk", "qt", "snappy_switcher"},
    "mono_font_size": {"alacritty", "ghostty", "qt"},
    "dark_hint":      {"gtk"},
}


def _header(colors: ColorScheme, comment: str) -> str:
    """Generated-file header for non-JSON targets."""
    return (
        f"{comment} Generated by apply-theme — do not edit\n"
        f"{comment} Source: {colors.family}-{colors.variant} | Variant: {colors.variant}\n"
    )


def _assemble(target: ModuleType, content: str | list[list[str]],
              colors: ColorScheme) -> None:
    """Write or execute content using the target's declared assembly strategy."""
    assembly = target.ASSEMBLY

    if assembly == "command":
        for cmd in content:
            try:
                subprocess.run(cmd, check=True, capture_output=True, text=True)
            except FileNotFoundError:
                print(f"  skip: {cmd[0]!r} not found", file=sys.stderr)
            except subprocess.CalledProcessError as exc:
                print(f"  warning: {cmd} failed: {exc.stderr.strip()}", file=sys.stderr)
        return

    out = Path(target.OUTPUT_PATH).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)

    comment = getattr(target, "COMMENT", None)

    if assembly in ("import", "standalone"):
        header = _header(colors, comment) + "\n" if comment else ""
        out.write_text(header + content)

    elif assembly == "concat":
        base_path = Path(target.BASE_PATH).expanduser()
        if not base_path.is_file():
            print(f"  skip: base file missing: {base_path}", file=sys.stderr)
            return

        # JSON merge variant (e.g. vicinae) — depth-1 merge preserves
        # nested dicts from both sides.
        if out.suffix == ".json":
            base_data = json.loads(base_path.read_text())
            gen_data = json.loads(content)
            merged = {**base_data}
            for k, v in gen_data.items():
                if k in merged and isinstance(merged[k], dict) and isinstance(v, dict):
                    merged[k] = {**merged[k], **v}
                else:
                    merged[k] = v
            out.write_text(json.dumps(merged, indent=2) + "\n")
        else:
            base = base_path.read_text()
            header = _header(colors, comment) + "\n" if comment else ""
            out.write_text(base.rstrip("\n") + "\n" + header + content)

    else:
        raise ValueError(f"Unknown assembly strategy: {assembly!r}")

    # Write to extra output paths (e.g. qt5ct equivalent of qt6ct scheme)
    for extra in getattr(target, "EXTRA_OUTPUTS", []):
        p = Path(extra).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(out.read_text())


def _reload(target: ModuleType, colors: ColorScheme, state: ThemeState) -> None:
    """Fire the target's reload command and/or on_apply hook."""
    cmd = getattr(target, "RELOAD_CMD", None)
    if cmd:
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True)
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            print(f"  reload warning ({target.TARGET_NAME}): {exc}", file=sys.stderr)
    fn = getattr(target, "on_apply", None)
    if fn:
        try:
            fn(colors, state)
        except Exception as exc:
            print(f"  reload warning ({target.TARGET_NAME}): {exc}", file=sys.stderr)


def apply_target(name: str, colors: ColorScheme, state: ThemeState) -> bool:
    """Run a single target by name. Returns True on success."""
    target = REGISTRY.get(name)
    if target is None:
        print(f"error: unknown target '{name}'", file=sys.stderr)
        return False
    try:
        content = target.generate(colors, state)
        _assemble(target, content, colors)
        _reload(target, colors, state)
        print(f"  {name}: ok")
        return True
    except Exception as exc:
        print(f"  {name}: FAILED — {exc}", file=sys.stderr)
        return False


def _sorted_targets(names: set[str]) -> list[str]:
    """Sort targets: file-writing first, command targets last, alpha within."""
    def _key(name: str) -> tuple[int, str]:
        t = REGISTRY.get(name)
        return (1 if t and t.ASSEMBLY == "command" else 0, name)
    return sorted(names, key=_key)


def apply_targets(names: set[str], colors: ColorScheme, state: ThemeState) -> None:
    """Run a set of targets, skipping any that aren't registered."""
    available = names & REGISTRY.keys()
    skipped = names - REGISTRY.keys()
    if skipped:
        print(f"  (skipping unregistered: {', '.join(sorted(skipped))})")
    for name in _sorted_targets(available):
        apply_target(name, colors, state)


def apply_all(colors: ColorScheme, state: ThemeState) -> None:
    """Run every registered target."""
    for name in _sorted_targets(set(REGISTRY)):
        apply_target(name, colors, state)


def targets_for_key(state_key: str, state: ThemeState | None = None) -> set[str]:
    """Return the set of target names affected by a state key change."""
    targets = set(DEPENDS.get(state_key, set()))
    if state_key == "color_scheme" and state is not None and not state.filter_wallpaper:
        targets.discard("wallpaper")
    return targets
