format = "$directory$all"
right_format = """$git_branch$git_status$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[line_break]
disabled = true

[character]
success_symbol = " [](bold #8aadf4)"
error_symbol = " [](#ed8796)"
vicmd_symbol = "[  ](#a6da95)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:bold #24273a bg:none)[$duration]($style)[](fg:bold #24273a bg:#24273a)[](fg:bold #c6a0f6 bg:#24273a)[ ](fg:#24273a bg:#c6a0f6)[](fg:#c6a0f6 bg:none) "
disabled = false
style = "fg:bold #f4dbd6 bg:#24273a"

[directory]
format = "[](fg:#24273a bg:none)[$path]($style)[](fg:#24273a bg:#24273a)[](fg:#8aadf4 bg:#24273a)[ ](fg:#24273a bg:#8aadf4)[](fg:#8aadf4 bg:none)"
style = "fg:bold #f4dbd6 bg:#24273a"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:#24273a bg:none)[$branch]($style)[](fg:#24273a bg:#24273a)[](fg:#a6da95 bg:#24273a)[](fg:#282c34 bg:#a6da95)[](fg:#a6da95 bg:none) "
style = "fg:bold #f4dbd6 bg:#24273a"

[git_status]
format="[](fg:#24273a bg:none)[$all_status$ahead_behind]($style)[](fg:#24273a bg:#24273a)[](fg:#8bd5ca bg:#24273a)[ ](fg:#24273a bg:#8bd5ca)[](fg:#8bd5ca bg:none) "
style = "fg:bold #f4dbd6 bg:#24273a"
conflicted = "="
ahead =	"${count}"
behind = "${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '