"""Cursor theme files plus best-effort live updates."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from themes.lib.schema import ColorScheme, ThemeState

TARGET_NAME = "cursor"
ASSEMBLY = "standalone"
OUTPUT_PATH = "~/.local/share/icons/default/index.theme.generated"
COMMENT = "#"

_HYPR_CURSOR_CONF = "~/.config/hypr/cursor.conf"
_XCURSOR_INDEX = "~/.local/share/icons/default/index.theme"
_LEGACY_XCURSOR_INDEX = "~/.icons/default/index.theme"
_HYPRCURSOR_THEME_MAP = {
    "BreezeX-RosePine-Linux": "rose-pine-hyprcursor",
}


def _index_theme_text(cursor_theme: str) -> str:
    return (
        "[Icon Theme]\n"
        "Name=Default\n"
        f"Inherits={cursor_theme}\n"
    )


def _dconf_set(key: str, value: str) -> None:
    _run(["dconf", "write", f"/org/gnome/desktop/interface/{key}", value])


def _run(cmd: list[str], *, env: dict[str, str] | None = None) -> None:
    subprocess.run(
        cmd,
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )


def _hyprctl_cursor_theme(cursor_theme: str) -> str:
    return _HYPRCURSOR_THEME_MAP.get(cursor_theme, cursor_theme)


def _hyprcursor_env_theme(cursor_theme: str) -> str | None:
    return _HYPRCURSOR_THEME_MAP.get(cursor_theme)


def _hyprctl_env(var: str, value: str) -> None:
    _run(["hyprctl", "keyword", "env", f"{var},{value}"])


def _import_user_env(values: dict[str, str]) -> None:
    env = dict(os.environ)
    env.update(values)
    try:
        _run(
            ["systemctl", "--user", "import-environment", *values.keys()],
            env=env,
        )
    except Exception:
        pass
    try:
        _run(
            [
                "dbus-update-activation-environment",
                "--systemd",
                *(f"{key}={value}" for key, value in values.items()),
            ]
        )
    except Exception:
        pass


def _unset_user_env(*keys: str) -> None:
    if not keys:
        return
    try:
        _run(["systemctl", "--user", "unset-environment", *keys])
    except Exception:
        pass
    try:
        _run(
            [
                "dbus-update-activation-environment",
                "--systemd",
                *(f"{key}=" for key in keys),
            ]
        )
    except Exception:
        pass


def generate(colors: ColorScheme, state: ThemeState) -> str:
    del colors
    return _index_theme_text(state.cursor_theme)


def persist(colors: ColorScheme, state: ThemeState) -> None:
    del colors
    generated_path = Path(OUTPUT_PATH).expanduser()
    xcursor_index = Path(_XCURSOR_INDEX).expanduser()
    legacy_index = Path(_LEGACY_XCURSOR_INDEX).expanduser()

    conf_path = Path(_HYPR_CURSOR_CONF).expanduser()
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by apply-theme -- do not edit",
        f"env = XCURSOR_THEME,{state.cursor_theme}",
        f"env = XCURSOR_SIZE,{state.cursor_size}",
    ]
    hyprcursor_theme = _hyprcursor_env_theme(state.cursor_theme)
    if hyprcursor_theme:
        lines.append(f"env = HYPRCURSOR_THEME,{hyprcursor_theme}")
    conf_path.write_text("\n".join(lines) + "\n")

    for index_path in (xcursor_index, legacy_index):
        index_path.parent.mkdir(parents=True, exist_ok=True)
        if index_path.is_symlink() or index_path.exists():
            index_path.unlink()
        try:
            index_path.symlink_to(generated_path)
        except OSError:
            index_path.write_text(_index_theme_text(state.cursor_theme))


def on_apply(colors: ColorScheme, state: ThemeState) -> None:
    del colors
    _dconf_set("cursor-theme", f"'{state.cursor_theme}'")
    _dconf_set("cursor-size", str(state.cursor_size))
    hyprcursor_theme = _hyprcursor_env_theme(state.cursor_theme)
    session_env = {
        "XCURSOR_THEME": state.cursor_theme,
        "XCURSOR_SIZE": str(state.cursor_size),
    }
    _hyprctl_env("XCURSOR_THEME", state.cursor_theme)
    _hyprctl_env("XCURSOR_SIZE", str(state.cursor_size))
    if hyprcursor_theme:
        _hyprctl_env("HYPRCURSOR_THEME", hyprcursor_theme)
        session_env["HYPRCURSOR_THEME"] = hyprcursor_theme
    else:
        _hyprctl_env("HYPRCURSOR_THEME", "")
    _run(["hyprctl", "setcursor", _hyprctl_cursor_theme(state.cursor_theme), str(state.cursor_size)])
    _import_user_env(session_env)
    if not hyprcursor_theme:
        _unset_user_env("HYPRCURSOR_THEME")
