use crate::{
    paths,
    theme::{
        self, json,
        schema::{ColorScheme, ThemeState},
        targets::{Assembly, GeneratedContent, Target, TargetRegistry},
    },
};
use serde_json::{Map, Value};
use std::{
    collections::BTreeSet,
    fs, io,
    path::{Path, PathBuf},
};

const COLOR_TARGETS: [&str; 18] = [
    "alacritty",
    "ghostty",
    "gtksourceview",
    "hyprland",
    "zathura",
    "quickshell",
    "neovim",
    "opencode",
    "starship",
    "tmux",
    "gtk",
    "qt",
    "vicinae",
    "bat",
    "vscode",
    "spicetify",
    "snappy_switcher",
    "zsh",
];
const WALLPAPER_TARGETS: [&str; 1] = ["wallpaper"];
const SYSTEM_FONT_TARGETS: [&str; 6] = [
    "chromium",
    "quickshell",
    "gtk",
    "qt",
    "vicinae",
    "snappy_switcher",
];
const MONO_FONT_TARGETS: [&str; 8] = [
    "alacritty",
    "chromium",
    "ghostty",
    "gtk",
    "neovide",
    "quickshell",
    "qt",
    "vscode",
];
const ICON_THEME_TARGETS: [&str; 3] = ["gtk", "qt", "snappy_switcher"];
const CURSOR_TARGETS: [&str; 1] = ["cursor"];
const FONT_SIZE_TARGETS: [&str; 4] = ["gtk", "qt", "quickshell", "snappy_switcher"];
const MONO_FONT_SIZE_TARGETS: [&str; 6] =
    ["alacritty", "ghostty", "gtk", "neovide", "qt", "vscode"];
const DARK_HINT_TARGETS: [&str; 1] = ["gtk"];
const HYPR_APPEARANCE_TARGETS: [&str; 1] = ["hypr_appearance"];

pub fn header(colors: &ColorScheme, comment: &str) -> String {
    format!(
        "{comment} Generated by apply-theme — do not edit\n{comment} Source: {}-{} | Variant: {}\n",
        colors.family, colors.variant, colors.variant
    )
}

pub fn apply_target(
    registry: &TargetRegistry,
    name: &str,
    colors: &ColorScheme,
    state: &ThemeState,
    runtime: bool,
) -> bool {
    let Some(target) = registry.get(name) else {
        eprintln!("error: unknown target '{name}'");
        return false;
    };

    let result = (|| -> crate::Result<()> {
        let content = target.generate(colors, state)?;
        assemble(target, content, colors)?;
        persist(target, colors, state)?;
        if runtime {
            reload(target, colors, state);
        }
        Ok(())
    })();

    match result {
        Ok(()) => {
            println!("  {name}: ok");
            true
        }
        Err(error) => {
            eprintln!("  {name}: FAILED — {error}");
            false
        }
    }
}

pub fn apply_targets<I, S>(
    registry: &TargetRegistry,
    names: I,
    colors: &ColorScheme,
    state: &ThemeState,
    runtime: bool,
) -> bool
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut available = Vec::new();
    let mut skipped = Vec::new();

    for name in names {
        let name = name.as_ref();
        if registry.get(name).is_some() {
            available.push(name.to_owned());
        } else {
            skipped.push(name.to_owned());
        }
    }

    if !skipped.is_empty() {
        skipped.sort();
        println!("  (skipping unregistered: {})", skipped.join(", "));
    }

    let mut ok = true;
    for name in sorted_targets(registry, available) {
        ok = apply_target(registry, &name, colors, state, runtime) && ok;
    }
    ok
}

pub fn apply_targets_quiet<I, S>(
    registry: &TargetRegistry,
    names: I,
    colors: &ColorScheme,
    state: &ThemeState,
    runtime: bool,
) -> crate::Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut available = Vec::new();

    for name in names {
        let name = name.as_ref();
        if registry.get(name).is_some() {
            available.push(name.to_owned());
        }
    }

    let mut failures = Vec::new();
    for name in sorted_targets(registry, available) {
        if let Err(error) = apply_target_quiet(registry, &name, colors, state, runtime) {
            failures.push(format!("{name}: {error}"));
        }
    }

    if failures.is_empty() {
        Ok(())
    } else {
        Err(io::Error::other(failures.join("; ")).into())
    }
}

pub fn apply_all(
    registry: &TargetRegistry,
    colors: &ColorScheme,
    state: &ThemeState,
    runtime: bool,
    sync_safe: bool,
) -> bool {
    let names = all_target_names(registry, sync_safe);
    apply_targets(registry, names, colors, state, runtime)
}

pub fn color_targets() -> BTreeSet<String> {
    named_targets(COLOR_TARGETS)
}

pub fn font_targets() -> BTreeSet<String> {
    named_targets(
        SYSTEM_FONT_TARGETS
            .iter()
            .chain(MONO_FONT_TARGETS.iter())
            .copied(),
    )
}

pub fn targets_for_key(state_key: &str, state: Option<&ThemeState>) -> BTreeSet<String> {
    let mut targets = match state_key {
        "color_scheme" => named_targets(
            COLOR_TARGETS
                .into_iter()
                .chain(std::iter::once("wallpaper")),
        ),
        _ => named_targets(dependency_targets(state_key).iter().copied()),
    };

    if state_key == "color_scheme" && matches!(state, Some(state) if !state.filter_wallpaper) {
        targets.remove("wallpaper");
    }

    targets
}

fn named_targets<I>(names: I) -> BTreeSet<String>
where
    I: IntoIterator<Item = &'static str>,
{
    names.into_iter().map(str::to_owned).collect()
}

fn dependency_targets(state_key: &str) -> &'static [&'static str] {
    match state_key {
        "wallpaper" | "filter_wallpaper" => &WALLPAPER_TARGETS,
        "system_font" => &SYSTEM_FONT_TARGETS,
        "mono_font" => &MONO_FONT_TARGETS,
        "icon_theme" => &ICON_THEME_TARGETS,
        "cursor_theme" | "cursor_size" => &CURSOR_TARGETS,
        "font_size" => &FONT_SIZE_TARGETS,
        "quickshell_font_size_offset" => &["quickshell"],
        "gtk_font_size_offset" => &["gtk"],
        "qt_font_size_offset" => &["qt"],
        "chromium_font_size_offset" => &[],
        "mono_font_size" => &MONO_FONT_SIZE_TARGETS,
        "alacritty_mono_font_size_offset" => &["alacritty"],
        "ghostty_mono_font_size_offset" => &["ghostty"],
        "gtk_mono_font_size_offset" => &["gtk"],
        "neovide_mono_font_size_offset" => &["neovide"],
        "qt_mono_font_size_offset" => &["qt"],
        "vscode_mono_font_size_offset" => &["vscode"],
        "dark_hint" => &DARK_HINT_TARGETS,
        "hypr_gaps_in"
        | "hypr_gaps_out"
        | "hypr_border_size"
        | "hypr_rounding"
        | "hypr_blur_enabled"
        | "hypr_blur_size"
        | "hypr_blur_passes"
        | "hypr_animations_enabled" => &HYPR_APPEARANCE_TARGETS,
        _ => &[],
    }
}

fn apply_target_quiet(
    registry: &TargetRegistry,
    name: &str,
    colors: &ColorScheme,
    state: &ThemeState,
    runtime: bool,
) -> crate::Result<()> {
    let target = registry.get(name).ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, format!("unknown target '{name}'"))
    })?;

    let content = target.generate(colors, state)?;
    assemble(target, content, colors)?;
    persist(target, colors, state)?;
    if runtime {
        reload_quiet(target, colors, state);
    }
    Ok(())
}

fn assemble(
    target: &dyn Target,
    content: GeneratedContent,
    colors: &ColorScheme,
) -> crate::Result<()> {
    let metadata = target.metadata();
    match metadata.assembly {
        Assembly::Command => run_command_batch(content),
        Assembly::Import | Assembly::Standalone => {
            let rendered = match content {
                GeneratedContent::Text(content) => {
                    let header = metadata
                        .comment
                        .map(|comment| format!("{}\n", header(colors, comment)))
                        .unwrap_or_default();
                    format!("{header}{content}")
                }
                GeneratedContent::Commands(_) => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!(
                            "Target '{}' returned commands for a file-writing assembly",
                            metadata.name
                        ),
                    )
                    .into());
                }
            };
            let output_path = output_path(metadata)?;
            write_output(&output_path, &rendered)?;
            write_extra_outputs(metadata, &rendered)?;
            Ok(())
        }
        Assembly::Concat => assemble_concat(metadata, content, colors),
    }
}

fn assemble_concat(
    metadata: &crate::theme::targets::TargetMetadata,
    content: GeneratedContent,
    colors: &ColorScheme,
) -> crate::Result<()> {
    let output_path = output_path(metadata)?;
    let base_path = base_path(metadata)?;

    if !base_path.exists() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!(
                "base file missing for target '{}': {}",
                metadata.name,
                base_path.display()
            ),
        )
        .into());
    }

    let rendered = match content {
        GeneratedContent::Text(content) => {
            if output_path
                .extension()
                .is_some_and(|extension| extension == "json")
            {
                concat_json(&base_path, &content)?
            } else {
                let base = fs::read_to_string(&base_path)?;
                let header = metadata
                    .comment
                    .map(|comment| format!("{}\n", header(colors, comment)))
                    .unwrap_or_default();
                format!("{}\n{header}{content}", trim_trailing_newlines(&base))
            }
        }
        GeneratedContent::Commands(_) => {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!(
                    "Target '{}' returned commands for concat assembly",
                    metadata.name
                ),
            )
            .into());
        }
    };

    write_output(&output_path, &rendered)?;
    write_extra_outputs(metadata, &rendered)?;
    Ok(())
}

fn concat_json(base_path: &Path, generated: &str) -> crate::Result<String> {
    let base_value: Value =
        serde_json::from_str(&fs::read_to_string(base_path)?).map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("Invalid JSON in {}: {error}", base_path.display()),
            )
        })?;
    let generated_value: Value = serde_json::from_str(generated).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("Invalid generated JSON for concat target: {error}"),
        )
    })?;

    let Value::Object(base_map) = base_value else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{}: expected top-level JSON object", base_path.display()),
        )
        .into());
    };
    let Value::Object(generated_map) = generated_value else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "Generated concat JSON must be a top-level object",
        )
        .into());
    };

    let merged = merge_json_objects(base_map, generated_map);
    Ok(format!(
        "{}\n",
        json::format_pretty_value(&Value::Object(merged))
    ))
}

fn merge_json_objects(
    base: Map<String, Value>,
    generated: Map<String, Value>,
) -> Map<String, Value> {
    let mut merged = base;

    for (key, value) in generated {
        match (merged.get_mut(&key), value) {
            (Some(Value::Object(base_child)), Value::Object(generated_child)) => {
                let mut merged_child = base_child.clone();
                for (nested_key, nested_value) in generated_child {
                    merged_child.insert(nested_key, nested_value);
                }
                *base_child = merged_child;
            }
            (_, value) => {
                merged.insert(key, value);
            }
        }
    }

    merged
}

fn persist(target: &dyn Target, colors: &ColorScheme, state: &ThemeState) -> crate::Result<()> {
    target.persist(colors, state)
}

fn reload(target: &dyn Target, colors: &ColorScheme, state: &ThemeState) {
    let metadata = target.metadata();

    if let Some(command) = metadata.reload_cmd
        && let Err(error) = run_command(command)
    {
        eprintln!("  reload warning ({}): {}", metadata.name, error);
    }

    if let Err(error) = target.on_apply(colors, state) {
        eprintln!("  reload warning ({}): {}", metadata.name, error);
    }
}

fn reload_quiet(target: &dyn Target, colors: &ColorScheme, state: &ThemeState) {
    let metadata = target.metadata();

    if let Some(command) = metadata.reload_cmd {
        let _ = run_command(command);
    }

    let _ = target.on_apply(colors, state);
}

fn run_command_batch(content: GeneratedContent) -> crate::Result<()> {
    let GeneratedContent::Commands(commands) = content else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "Command target returned text instead of commands",
        )
        .into());
    };

    let mut failures = Vec::new();
    for command in commands {
        if let Err(error) = run_owned_command(&command) {
            failures.push(error.to_string());
        }
    }

    if failures.is_empty() {
        Ok(())
    } else {
        Err(io::Error::other(failures.join("; ")).into())
    }
}

fn run_command(command: &[&str]) -> crate::Result<()> {
    theme::run_command(command)
}

fn run_owned_command(command: &[String]) -> crate::Result<()> {
    theme::run_owned_command(command)
}

fn write_output(path: &Path, content: &str) -> crate::Result<()> {
    theme::atomic_write(path, content.as_bytes())
}

fn write_extra_outputs(
    metadata: &crate::theme::targets::TargetMetadata,
    content: &str,
) -> crate::Result<()> {
    for extra in metadata.extra_outputs {
        let path = theme::expand_user_path(extra)?;
        write_output(&path, content)?;
    }
    Ok(())
}

fn output_path(
    metadata: &crate::theme::targets::TargetMetadata,
) -> crate::Result<std::path::PathBuf> {
    let path = metadata.output_path.ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Target '{}' is missing OUTPUT_PATH", metadata.name),
        )
    })?;
    theme::expand_user_path(path)
}

fn base_path(metadata: &crate::theme::targets::TargetMetadata) -> crate::Result<PathBuf> {
    let path = metadata.base_path.ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Target '{}' is missing BASE_PATH", metadata.name),
        )
    })?;
    resolve_base_path(path)
}

fn resolve_base_path(path: &str) -> crate::Result<PathBuf> {
    let candidate = Path::new(path);
    if path.starts_with('~') || candidate.is_absolute() {
        return theme::expand_user_path(path);
    }

    Ok(paths::repo_path(candidate)?)
}

fn trim_trailing_newlines(text: &str) -> &str {
    text.trim_end_matches('\n')
}

fn sorted_targets(registry: &TargetRegistry, mut names: Vec<String>) -> Vec<String> {
    names.sort_by(|left, right| {
        let left_key = target_sort_key(registry, left);
        let right_key = target_sort_key(registry, right);
        left_key.cmp(&right_key)
    });
    names
}

fn target_sort_key<'a>(registry: &TargetRegistry, name: &'a str) -> (u8, &'a str) {
    let assembly_rank = registry
        .get(name)
        .map(|target| target.metadata().assembly)
        .map(|assembly| if assembly == Assembly::Command { 1 } else { 0 })
        .unwrap_or(0);

    (assembly_rank, name)
}

fn all_target_names(registry: &TargetRegistry, sync_safe: bool) -> Vec<String> {
    registry
        .iter()
        .filter(|(_, target)| !sync_safe || target.metadata().sync_safe)
        .map(|(name, _)| name.to_owned())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::targets::{GeneratedContent, TargetMetadata};
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn dummy_colors() -> ColorScheme {
        serde_json::from_value(serde_json::json!({
            "family": "gruvbox",
            "variant": "dark",
            "appearance": "dark",
            "colors": {
                "bg": "#000000",
                "bg_dim": "#010101",
                "bg1": "#020202",
                "bg2": "#030303",
                "bg3": "#040404",
                "fg": "#f0f0f0",
                "fg2": "#e0e0e0",
                "fg3": "#d0d0d0",
                "fg4": "#c0c0c0",
                "red": "#ff0000",
                "green": "#00ff00",
                "yellow": "#ffff00",
                "blue": "#0000ff",
                "purple": "#ff00ff",
                "cyan": "#00ffff",
                "orange": "#ff8800",
                "accent": "#3366ff",
                "red_bright": "#ff1111",
                "green_bright": "#11ff11",
                "yellow_bright": "#ffff11",
                "blue_bright": "#1111ff",
                "purple_bright": "#ff11ff",
                "cyan_bright": "#11ffff",
                "orange_bright": "#ff9911"
            },
            "palette": [
                "#000000", "#111111", "#222222", "#333333",
                "#444444", "#555555", "#666666", "#777777",
                "#888888", "#999999", "#aaaaaa", "#bbbbbb",
                "#cccccc", "#dddddd", "#eeeeee", "#ffffff"
            ]
        }))
        .expect("valid dummy colors")
    }

    fn dummy_state(filter_wallpaper: bool) -> ThemeState {
        ThemeState {
            color_scheme: "gruvbox-dark".to_owned(),
            wallpaper: "/tmp/wallpaper.png".to_owned(),
            filter_wallpaper,
            system_font: "Overpass".to_owned(),
            mono_font: "JetBrains Mono Nerd Font".to_owned(),
            icon_theme: "Neuwaita".to_owned(),
            cursor_theme: "BreezeX-RosePine-Linux".to_owned(),
            cursor_size: 24,
            font_size: 11,
            quickshell_font_size_offset: 0,
            gtk_font_size_offset: 0,
            qt_font_size_offset: 0,
            chromium_font_size_offset: 0,
            mono_font_size: 11,
            alacritty_mono_font_size_offset: 0,
            ghostty_mono_font_size_offset: 0,
            gtk_mono_font_size_offset: 0,
            neovide_mono_font_size_offset: 0,
            qt_mono_font_size_offset: 0,
            vscode_mono_font_size_offset: 3,
            dark_hint: false,
            hypr_gaps_in: 4,
            hypr_gaps_out: 6,
            hypr_border_size: 0,
            hypr_rounding: 8,
            hypr_blur_enabled: false,
            hypr_blur_size: 3,
            hypr_blur_passes: 4,
            hypr_animations_enabled: true,
            extra: Map::new(),
        }
    }

    fn noop_generate(
        _colors: &ColorScheme,
        _state: &ThemeState,
    ) -> crate::Result<GeneratedContent> {
        Ok(GeneratedContent::text("content\n"))
    }

    fn unique_path(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time works")
            .as_nanos();
        std::env::temp_dir().join(format!("desktopctl-theme-{name}-{nanos}"))
    }

    #[test]
    fn targets_for_color_scheme_skips_wallpaper_when_filtering_is_disabled() {
        let state = dummy_state(false);
        let targets = targets_for_key("color_scheme", Some(&state));
        assert!(!targets.contains("wallpaper"));
    }

    #[test]
    fn targets_for_color_scheme_keeps_wallpaper_when_filtering_is_enabled() {
        let state = dummy_state(true);
        let targets = targets_for_key("color_scheme", Some(&state));
        assert!(targets.contains("wallpaper"));
    }

    #[test]
    fn targets_for_color_scheme_include_opencode() {
        let state = dummy_state(true);
        let targets = targets_for_key("color_scheme", Some(&state));
        assert!(targets.contains("opencode"));
    }

    #[test]
    fn targets_for_color_scheme_include_zsh() {
        let state = dummy_state(true);
        let targets = targets_for_key("color_scheme", Some(&state));
        assert!(targets.contains("zsh"));
    }

    #[test]
    fn quickshell_font_size_offset_targets_only_quickshell() {
        let targets = targets_for_key("quickshell_font_size_offset", None)
            .into_iter()
            .collect::<Vec<_>>();
        assert_eq!(targets, vec!["quickshell".to_owned()]);
    }

    #[test]
    fn gtk_font_size_offset_targets_only_gtk() {
        let targets = targets_for_key("gtk_font_size_offset", None)
            .into_iter()
            .collect::<Vec<_>>();
        assert_eq!(targets, vec!["gtk".to_owned()]);
    }

    #[test]
    fn qt_font_size_offset_targets_only_qt() {
        let targets = targets_for_key("qt_font_size_offset", None)
            .into_iter()
            .collect::<Vec<_>>();
        assert_eq!(targets, vec!["qt".to_owned()]);
    }

    #[test]
    fn chromium_font_size_offset_has_no_targets() {
        let targets = targets_for_key("chromium_font_size_offset", None)
            .into_iter()
            .collect::<Vec<_>>();
        assert!(targets.is_empty());
    }

    #[test]
    fn font_size_does_not_target_chromium() {
        let targets = targets_for_key("font_size", None);
        assert!(!targets.contains("chromium"));
    }

    #[test]
    fn mono_font_size_does_not_target_chromium() {
        let targets = targets_for_key("mono_font_size", None);
        assert!(!targets.contains("chromium"));
    }

    #[test]
    fn mono_font_does_not_target_tmux() {
        let targets = targets_for_key("mono_font", None);
        assert!(!targets.contains("tmux"));
    }

    #[test]
    fn apply_all_filters_sync_safe_targets() -> crate::Result<()> {
        let mut registry = TargetRegistry::new();
        let out_dir = unique_path("sync-safe");
        let safe_path = out_dir.join("safe.conf");
        let unsafe_path = out_dir.join("unsafe.conf");

        registry.register_function(
            TargetMetadata {
                name: "safe",
                assembly: Assembly::Standalone,
                output_path: Some(Box::leak(
                    safe_path.to_string_lossy().into_owned().into_boxed_str(),
                )),
                base_path: None,
                extra_outputs: &[],
                managed_paths: &[],
                reload_cmd: None,
                comment: Some("#"),
                sync_safe: true,
            },
            noop_generate,
        )?;
        registry.register_function(
            TargetMetadata {
                name: "unsafe",
                assembly: Assembly::Standalone,
                output_path: Some(Box::leak(
                    unsafe_path.to_string_lossy().into_owned().into_boxed_str(),
                )),
                base_path: None,
                extra_outputs: &[],
                managed_paths: &[],
                reload_cmd: None,
                comment: Some("#"),
                sync_safe: false,
            },
            noop_generate,
        )?;

        let ok = apply_all(&registry, &dummy_colors(), &dummy_state(false), false, true);
        assert!(ok);
        assert!(safe_path.is_file());
        assert!(!unsafe_path.exists());

        fs::remove_dir_all(out_dir)?;
        Ok(())
    }
}
